# Generated by Django 4.0 on 2022-04-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_no',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
