# Generated by Django 4.0 on 2022-03-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_bkash_verified',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone_number',
        ),
    ]
