# Generated by Django 4.0 on 2022-04-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_payment_is_bkash_verified_remove_payment_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Shipped', max_length=100),
        ),
    ]
